### ISSUE TITLE
Replace the binary search function in utils.R

### ISSUE THREAD

**Issue by corwinjoy** [joshuaulrich/xts#101]
Binary search is famously easy to get wrong - and it took almost 20 years to get the first bug free version. (See the article below).  When I look at the .binsearch method I see several red flags:
1. The code uses
mid <- round((lo + hi) / 2)
This is a well known binary search bug that can give an overflow error.
1. Round rounds up instead of down as seen in standard algorithms.  I don't know if this causes a potential error.
2. I see the invariant
   if(mid == 0) return(NA)
   I don't understand how that condition is possible and what this is trying to prevent.
3. I see "dirt" in the routine like multiple checks for mid ==0 and an errant assignment for i < -1 suggesting this code is not well reviewed.
4. The start = TRUE logic is embedded in the search loop for further complexity.

The bottom line is that getting binary search right is surprisingly hard, and it's easy to end up with a lurking error even if you are an expert.  In this case, the code doesn't look as solid as I would like.  I would propose the use of a library routine (binsearch, std::lower_bound) or shrink the main part to a 4 line standard search so it is more easily verified.

See, e.g.
http://stackoverflow.com/questions/504335/what-are-the-pitfalls-in-implementing-binary-search

"This question was just asked again recently. Apart from Knuth's quote that "Although the basic idea of binary search is comparatively straightforward, the details can be surprisingly tricky", there is the staggering historical fact (see TAOCP, Volume 3, section 6.2.1) that binary search was first published in 1946 but the first published binary search without bugs was in 1962. And there is Bentley's experience that when he assigned binary search in courses for professional programmers at places like Bell Labs and IBM and gave them two hours, everyone reported they had got it right, and on examining their code 90% of them had bugs — year after year...."

Example binary search from 
https://www.topcoder.com/community/data-science/data-science-tutorials/binary-search/

``` java
binary_search(A, target):
   lo = 1, hi = size(A)
   while lo <= hi:
      mid = lo + (hi-lo)/2
      if A[mid] == target:
         return mid            
      else if A[mid] < target: 
         lo = mid+1
      else:
         hi = mid-1

   // target was not found
```

**Comment by joshuaulrich** [comment]
Note that `.binsearch` isn't currently used.  Though your comments likely apply to the C implementation in `src/binsearch.c` that the `binsearch` R function calls.

**Comment by joshuaulrich** [comment]
The `.binsearch()` function in `R/utils.R` was deleted as part of #100, so I am closing this issue because it is no longer relevant to the current code.
