### ISSUE TITLE
Allow more user control of axis formatting

### ISSUE THREAD

**Issue by rossb34** [joshuaulrich/xts#102]
Allowing for more user control of the axis formatting with ticks, labels, etc. stems from an email thread with Mauricio Zambrano-Bigiarini, the maintainer of hydroGOF and hydroTSM.

One specific case is  controlling the frequency of x-axis tick marks.
`grid.ticks.on` is an argument in `plot.xts` but is not passed to `axTicksByTIme` for the x-axis labels or  `axTicksByTIme2` for the grid tick marks. We should support `c(‘auto’, ‘years’, ‘quarters’, ‘months’,‘weeks’, ‘days’, ‘hours’, ‘minutes’, ‘seconds’)` for the `grid.ticks.on` argument.

**Comment by hzambran** [comment]
Thanks Ross for fixing the previous bug and providing a new branch.

However,  I'm still not able to customise the position of the labels,
because `grid.ticks.on` only controls where the grids are drawn.

Could it be possible to keep the old `major.ticks = "auto"` and
`minor.ticks = TRUE` arguments, in a way to use the first one to draw
the ticks for the labels and the second for drawing the minor ticks ?

For example, using the current names of the arguments, you could have:
`grid.major.ticks.on="auto"`
`grid.minor.ticks.on="auto"`

 where `"observation.based"` could be a possible option for `grid.minor.ticks.on`

In the same way, if I would like to customise the position of the ticks and labels of the vertical axis (I use them less frequently, but I do use them), how could I do  it with the current package ?

**Comment by braverock** [comment]
On 06/08/2015 12:34 AM, Mauricio Zambrano-Bigiarini wrote:
> Could it be possible to keep the old |major.ticks = "auto"| and
> |minor.ticks = TRUE| arguments, in a way to use the first one to draw
> the ticks for the labels and the second for drawing the minor ticks ?
>
> For example, using the current names of the arguments, you could have:
> |grid.major.ticks.on="auto"|
> |grid.minor.ticks.on="auto"|
>
> where |"observation.based"| could be a possible option for
> |grid.minor.ticks.on|

I like the idea of "major.ticks" and "minor.ticks" arguments.  We used 
these pretty frequently for certain charting types.

an "observations" argument would be consistent with "weeks", "seconds", 
etc.

> In the same way, if I would like to customise the position of the ticks
> and labels of the vertical axis (I use them less frequently, but I do
> use them), how could I do it with the current package ?

AxTicksByTime only works to sort out periodicity of the time axis. 
Right now I think we let R do most of the heavy lifting on the y axis.

**Comment by rossb34** [comment]
In reply to @hzambran :
> However, I'm still not able to customise the position of the labels, because `grid.ticks.on` only controls where the grids are drawn.

In the axis_formatting branch, the `grid.ticks.on` argument controls both the axis ticks and the grid.

> Could it be possible to keep the old `major.ticks = "auto"` and `minor.ticks = TRUE` arguments, in a way to use the first one to draw the ticks for the labels and the second for drawing the minor ticks ?

It would certainly be possible to have arguments to separately control the axis ticks and the grid ticks,.

> In the same way, if I would like to customise the position of the ticks and labels of the vertical axis (I use them less frequently, but I do use them), how could I do it with the current package ?

Currently supported customization for the vertical axis
* left/right axis, `yaxis.left` and `yaxis.right`
* string rotation, `srt` (same as in `par`)
* character expansion, `cex.axis`
* color, `labels.col`

The vertical axis tick marks and grid lines are drawn based on the range of the data for a given panel using the `pretty` function.

**Comment by hzambran** [comment]
In reply to @rossb34 :

> In the axis_formatting branch, the `grid.ticks.on` argument controls both the axis ticks and the grid. 

Exactly. However, I would like to be able to set a given frequency for the `ticks` and a **different** frequency for the labels. For example:

 
    x <- xts(rnorm(732),as.Date(13514:14245,origin="1970-01-01"))
    plot.xts(x, axes=FALSE, type="o", grid.ticks.on="years", cex.axis=1.1, major.ticks="months", minor.ticks="days")

> It would certainly be possible to have arguments to separately control the axis ticks and the grid ticks,.

In addition to `grid.ticks.on`, could you add `major.ticks` and `minor.ticks` arguments in `xts` before launching the new version ?

**Comment by hzambran** [comment]
Thank you very much !.

One minor comment/request:

would it be possible to put in bold the the ticks corresponding to 'major.ticks' and/or to make them a little bit longer than those corresponding to 'minor.ticks'  (resembling the current stable version of xts)?
