### ISSUE TITLE
`observation.based` not working

### ISSUE THREAD

**Issue by hzambran** [joshuaulrich/xts#104]
In the `axis_formatting` branch, the `observation.based` argument seems not to be working:

    x <- xts(rnorm(732),as.Date(13514:14245,origin="1970-01-01"))
    plot.xts(x, type="o", grid.ticks.on="months", observation.based=TRUE)

**Comment by rossb34** [comment]
The `observation.based` argument controls the spacing of data points along the x-axis. If `observation.based=TRUE`, the observations are drawn with equal spacing. If `observation.based=FALE`, the observations are drawn based on the time index of the data. An example use case of this is useful if you have daily data with no weekend observations, but you want the appearance of equally spaced data.
```
library(xts)
dat.xts <- .xts(1:20, c(1:10, 101:110))
plot(dat.xts)
![rplot1](https://cloud.githubusercontent.com/assets/5797430/8144098/eaade522-1199-11e5-9ba5-ec98144ff02e.png)
plot(dat.xts, observation.based = TRUE)
![rplot2](https://cloud.githubusercontent.com/assets/5797430/8144101/f767e18c-1199-11e5-9dbe-14c2873d83f5.png)

```

**Comment by hzambran** [comment]
Thanks for the explanation. I thought `observation.based` was meant to draw the tick marks on the x axis.

I just noticed that  `observation.based` considers NA values has valid data to draw the observations:

    library(xts)
    x <- xts(rnorm(732),as.Date(13514:14245,origin="1970-01-01"))
    x1           <- x
    x1[c(2:30),] <- NA
    x2           <- x[-c(2:30),]

    plot.xts(x1, type="o", grid.ticks.on="months", observation.based=TRUE)
    plot.xts(x1, type="o", grid.ticks.on="months", observation.based=FALSE)
    plot.xts(x2, type="o", grid.ticks.on="months", observation.based=TRUE)
    plot.xts(x2, type="o", grid.ticks.on="months", observation.based=FALSE)

Considering that in some circumstances the frequency of data recording is fixed and absence of data (e.g., on weekends) is recorded as `NA`, would you consider to draw the observations based on the  time index of valid data only (`!= NA`) ?

**Comment by rossb34** [comment]
I don't think we'll do any special handling of NAs.  This behavior is consistent with
  * the old plot.xts, plot.zoo, and other time series plotting. 
  * This is also a feature that allows us to easily overlay datapoints that have a different starting index, e.g. moving averages.

It is easy enough to use `na.omit` and the `observeration.based` argument to achieve the custom behavior for handling data with NAs based on his/her needs.

**Comment by hzambran** [comment]
`na.omit` is not documented in the current version of `plot.xts` (*axis_formatting* branch) and it seems not to be working along with `observeration.based`:

    library(xts)
    x <- xts(rnorm(30),as.Date(13514:13543,origin="1970-01-01"))
    x1           <- x
    x1[c(2:15),] <- NA
    x2           <- x[-c(2:15),]

    plot.xts(x1, type="o", grid.ticks.on="weeks", observation.based=TRUE, na.omit=TRUE)
    plot.xts(x1, type="o", grid.ticks.on="weeks", observation.based=FALSE, na.omit=TRUE)

**Comment by rossb34** [comment]
I did not mean to imply that `na.omit` is an argument to `plot.xts`. What I meant was that you can use the `na.omit` function like below.

```
library(xts)
set.seed(123)
x <- xts(rnorm(30),as.Date(13514:13543,origin="1970-01-01"))
x1           <- x
x1[c(2:15),] <- NA
x2           <- x[-c(2:15),]

plot.xts(na.omit(x1), type="o", grid.ticks.on="weeks", observation.based=TRUE)
plot.xts(na.omit(x1), type="o", grid.ticks.on="weeks", observation.based=FALSE)
```

**Comment by hzambran** [comment]
Thank you very much for clarifying this point !
