### ISSUE TITLE
ignore timezone on xts.print

### ISSUE THREAD

**Issue by jangorecki** [joshuaulrich/xts#109]
Having the different timezone on my local machine than the timezone of the xts object each print of the xts will raise following warning:
```
1: timezone of object (UTC) is different than current timezone (). 
```
I work in different timezones but I always work with UTC data.
Would be handy to suppress that type of warning globally, maybe an option `options("xts.print.ignore.tz"=TRUE)`?
That would be pretty simple PR in [indexTZ.R#L84](https://github.com/joshuaulrich/xts/blob/0947bf649a3c149c2bd4cc1c06cad51a4019cc94/R/indexTZ.R#L84), if you agree to merge it I can prepare it.

**Comment by joshuaulrich** [comment]
It already exists.  Look at lines [68 and 69](https://github.com/joshuaulrich/xts/blob/0947bf649a3c149c2bd4cc1c06cad51a4019cc94/R/indexTZ.R#L68-69).  Set `options(xts_check_TZ=FALSE)`.

**Comment by jangorecki** [comment]
huh, great! thanks for info
