### ISSUE TITLE
Allow for higher frequency gridlines and axis ticks

### ISSUE THREAD

**Issue by rossb34** [joshuaulrich/xts#115]
`axTicksByTime2` only supports ticks on years, months, weeks, and days. This is fine for low frequency data, but not for high frequency data. The `ticks.on` argument should support the same arguments for `on` in the function `endpoints`. This change will support gridlines and axis ticks for plotting high frequency data.

**Comment by joshuaulrich** [comment]
Fixed in 3d10049f47c4639aa20a75c9490b75390f1a6ed1.
