### ISSUE TITLE
[R-Forge #2753] which.i argument ignored with zero-width xts

### ISSUE THREAD

**Issue by joshuaulrich** [joshuaulrich/xts#12]
Submitted by: Garrett See
Assigned to: Joshua Ulrich
[R-Forge link](http://r-forge.r-project.org/tracker/index.php?func=detail&aid=2753&group_id=118&atid=516)

This is the unexpected behavior:

> x <- .xts(, 1:10)
> x[endpoints(x, 'seconds', 3), which.i=TRUE]
                    [,1]
1969-12-31 18:00:02   NA
1969-12-31 18:00:05   NA
1969-12-31 18:00:08   NA
1969-12-31 18:00:10   NA

I expected it to give the same result as an object that has a column:

> x <- .xts(rep(42, 10), 1:10)
> x[endpoints(x, 'seconds', 3), which.i=TRUE]
[1]  2  5  8 10

> packageVersion('xts')
[1] ‘0.9.3.2’

Followups:

Date: 2013-08-26 12:59
Sender: Joshua Ulrich
Fixed in r789.

**Comment by michaelsbradleyjr** [comment]
Has there been a regression with this bug? I'm getting the previous unexpected behavior with `xts` version `0.9-7`.

**Comment by joshuaulrich** [comment]
There may have been, but there's no issue with the current development version.

```r
R> x <- .xts(, 1:10)
R> x[endpoints(x, 'seconds', 3), which.i=TRUE]
[1]  2  5  8 10
R> packageVersion('xts')
[1] ‘0.10.0’
```

**Comment by michaelsbradleyjr** [comment]
Installed the current dev version via `devtools`, works great, thanks!
