### ISSUE TITLE
Errors in na.omit.xts when using snowfall

### ISSUE THREAD

**Issue by TomAndrews** [joshuaulrich/xts#122]
I apologise in advance for what is a very vague bug report, but any help tracking down the problem would be much appreciated.

I am using `xts` for time-series analysis along with `snowfall` (which is a wrapper around `snow`) to parallelize the job.  Every so often when running in parallel I get an error like:

```
Error in checkForRemoteErrors(val) : 
  one node produced an error: LOGICAL() can only be applied to a 'logical', not a 'character'
```

Unfortunately this isn't reproducible - re-running the job will normally fix it and I have never come across this error when running on only one cpu.  I would guess that the error occurs around 1-2% of the time on a 24 cpu cluster.

To try and track it down, I have set up my code so that it dumps the frames and a call stack on the worker nodes when it encounters an error.  The errors all seem to be in `na.omit.xts`, though the function calling `na.omit` varies.

If I load the frame dump then I can successfully run `na.omit.xts` on the input data, so I'm not sure where to look next.

In case it helps I have seen various permutations on the error message:

```
LOGICAL() can only be applied to a 'logical', not a 'builtin'
LOGICAL() can only be applied to a 'logical', not a 'integer'
```

I guess the error is being thrown from here:
https://github.com/joshuaulrich/xts/blob/master/src/leadingNA.c#L41

But that's just a guess.  Could `na.omit` not be thread-safe somehow?  As I said, any pointers on how to debug this would be much appreciated.

**Comment by joshuaulrich** [comment]
Can you please provide the full error messages, frames, and call stacks you have captured?  I understand if the frames contain proprietary data, but the error messages and call stacks will be helpful.

**Comment by TomAndrews** [comment]
Let me see what I can send.  Is it OK if I email you directly?

**Comment by joshuaulrich** [comment]
Certainly, if you prefer it not be public.

**Comment by joshuaulrich** [comment]
In our email conversation, you provided the `sessionInfo` output below, which shows you're using the CRAN version of xts.  Can you please upgrade to the latest xts on GitHub and re-run your code?

My current hypothesis is that the issue is not in `na.omit.xts` itself, but is due to memory corruption and just happens to manifest in that call. There have been a handful of memory-related issues fixed since 0.9-7, so I hope that one of them is the cause and upgrading fixes your issue.

```r
> sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Fedora 22 (Twenty Two)

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] sandwich_2.3-2   lmtest_0.9-34    R.cache_0.10.0   snowfall_1.84-6
[5] snow_0.3-13      xts_0.9-7        zoo_1.7-12       timeDate_3010.98

loaded via a namespace (and not attached):
[1] R.methodsS3_1.6.1 grid_3.2.2        R.utils_1.32.4    R.oo_1.18.0
[5] lattice_0.20-33
```

**Comment by TomAndrews** [comment]
Thanks for looking into it.  I'll try to get the GitHub version installed and let you know if it solves the problem.

**Comment by TomAndrews** [comment]
I have installed the latest version of xts from git and ran a big job and unfortunately I still get the same error:
```
Error in checkForRemoteErrors(val) : 
  one node produced an error: LOGICAL() can only be applied to a 'logical', not a 'character'
```
Again, this is being triggered from `na.omit.xts`.

My revised `sessionInfo` output:
```
R version 3.2.2 (2015-08-14)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Fedora 22 (Twenty Two)

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] TTR_0.23-0       sandwich_2.3-2   lmtest_0.9-34    R.cache_0.10.0
[5] snowfall_1.84-6  snow_0.3-13      xts_0.9-8        zoo_1.7-12
[9] timeDate_3010.98

loaded via a namespace (and not attached):
[1] R.methodsS3_1.6.1 grid_3.2.2        R.utils_1.32.4    R.oo_1.18.0
[5] lattice_0.20-33
```

As before, if I load the saved frames from the error, I can successfully run the call to `na.omit` that caused the error to be thrown when running in parallel.

Do you have any suggestions for trying to debug this?  Thanks.

**Comment by joshuaulrich** [comment]
I'm able to replicate similar behavior with the code below:

```r
R> x <- .xts(c(1,NA,1), 1:3)
R> gctorture(TRUE)
R> na.omit(x)
Error in na.omit.xts(x) : 
  LOGICAL() can only be applied to a 'logical', not a 'integer'
```

**Comment by TomAndrews** [comment]
Thanks, I'll get this installed and let you know how it goes.

**Comment by TomAndrews** [comment]
I got this installed yesterday and no errors so far.  I think if it's still OK over the next week we can declare it fixed.  Thanks for looking into it.

**Comment by joshuaulrich** [comment]
Thanks for the report.  Please close this issue when you're satisfied that it's fixed.

**Comment by TomAndrews** [comment]
There haven't been any more errors so I think that's fixed the problem.  Thanks very much for your help.
