### ISSUE TITLE
Analogue to polygon

### ISSUE THREAD

**Issue by joshuaulrich** [joshuaulrich/xts#132]
We have analogues for `lines` and `points` (`addLines` and `addPoints`, respectively).  It would be nice to have an `addPolygon` as well.

@eddelbuettel has a nice use-case in one of his [blog posts](http://dirk.eddelbuettel.com/blog/2011/01/16/).

**Comment by rossb34** [comment]
Initial prototype replicates chart in @eddelbuettel's blog post
```
library(quantmod)
library(TTR)

years <- 2
n <- 50
symbol <- "^GSPC"

today <- as.Date("2011-01-16")
X <- getSymbols(symbol, src="yahoo", from=format(today-365*years-2*n), to=today, auto.assign=FALSE)
x <- X[,6]                          # use Adjusted

xd <- SMA(x,n)
xv <- runSD(x, n)                   # compute xv as the rolling volatility
strt <- paste(format(today-365*years), "::", today, sep="")
x  <- x[strt]                       # subset plotting range using xts' nice functionality
xd <- xd[strt]
xv <- xv[strt]

fairlylight <- rgb(204/255, 204/255, 204/255, alpha=0.5)         # two suitable grays, with alpha-blending at 50%
verylight <- rgb(242/255, 242/255, 242/255, alpha=0.5)

plot(x, grid.ticks.on = "years")
# specify y coordinates as a single xts object with upper and lower coordinates for
# the vertices of the polygon
addPolygon(cbind(xd+xv, xd+2*xv), on = 1, col=fairlylight)
addPolygon(cbind(xd-xv, xd-2*xv), on = 1, col=fairlylight)
addPolygon(cbind(xd-xv, xd+xv), on = 1, col=verylight)
lines(xd, col="blue")
``` 
![rplot](https://cloud.githubusercontent.com/assets/5797430/13734193/6f3bc906-e969-11e5-8af4-bf4751fa379c.png)

Any feedback or suggestions for specifying the coordinates of the vertices of the polygon?

**Comment by eddelbuettel** [comment]
Nice!

**Comment by joshuaulrich** [comment]
I think the `addPolygon` function should be general, and should have a function signature similar to `polygon`.  When calling `polygon` inside `addPolygon`, `x` will usually be the xts index. But it might be nice to provide the flexibility to specify the `addPolygon` call with something other than an xts object.

My suggestion would be to add a `y = NULL` argument after `x` (akin to `polygon`'s first 2 arguments).  I don't think we need to support this for a first release, so we should check if `y` is non-null and throw an error.

We should also call `try.xts` on `x` to see if we can convert `x` to xts and throw an error if we cannot.  We should also ensure `x` has 2 columns for this first release.
