### ISSUE TITLE
bad link at https://cran.r-project.org/web/packages/xts/index.html

### ISSUE THREAD

**Issue by matkoniecz** [joshuaulrich/xts#133]
https://cran.r-project.org/web/packages/xts/index.html links to http://r-forge.r-project.org/projects/xts/

**Comment by joshuaulrich** [comment]
That's because CRAN has xts_0.9-7. As you can see from the [DESCRIPTION file](https://github.com/joshuaulrich/xts/blob/master/DESCRIPTION), this has already been fixed and it will be reflected on CRAN as soon as a new version is submitted.
