### ISSUE TITLE
as.Date incorrectly handles redirection to `as.Date` methods

### ISSUE THREAD

**Issue by jangorecki** [joshuaulrich/xts#137]
Reproduced on latest xts.
Attaching `xts` mask base `as.Date` and incorrectly handles redirection to `as.Date` methods:
```r
library(data.table)
x = as.IDate("2016-01-15")
class(as.Date(x))
#[1] "Date"
library(xts)
class(as.Date(x))
#[1] "IDate" "Date" 
class(data.table:::as.Date.IDate(x))
#[1] "Date"
```

**Comment by joshuaulrich** [comment]
Note:

```r
R> library(xts)
Loading required package: zoo

Attaching package: ‘zoo’

The following objects are masked from ‘package:base’:

    as.Date, as.Date.numeric


Attaching package: ‘xts’

The following object is masked from ‘package:data.table’:

    last
```

This is only related to xts in the sense that xts extends zoo, and depends on zoo in order to avoid having to re-export all zoo functions when xts is attached.  In other words, there's nothing I can do in xts to fix this, since I'm not going to re-export all zoo functions.

**Comment by jangorecki** [comment]
Huh, sorry, such a stupid mistake...
Will report to zoo.
