### ISSUE TITLE
Subset on multiple ISO datetimes?

### ISSUE THREAD

**Issue by michaelsbradleyjr** [joshuaulrich/xts#142]
Suppose I have a large xts object `myXts` which has a wide time index, e.g. all the seconds for a year or more.

For every day in the series, I'm interested in what happens during a set of times, e.g. `want_subset <- c("T02:00/T02:14:59", T04:15/T04:19:59", ...)`.

I'd like to be able to do the subsetting all in one go: `myXts[want_subset]`.

But that doesn't seem to work.  Some workarounds I've tried include using `Map` to subset across the individual pieces of `want_subset`, and then binding the list of results together; but repeatedly scanning the large index of `myXts` is a performance killer, i.e. as `want_subset` grows.

Another workaround I've found involves manually building a midnight-offset table and using it in combination with `findInterval` or `%in%` to scan across `.index(myXts)` a minimal number of times. Both approaches deliver acceptable performance, *much* faster than using `Map` and combining the results.

Still, it would be nice to be able to simply pass in a vector of ISO 8601 time ranges – less code written by me, easier to understand upon later review.

Have I misunderstood and what I want to do is already possible using ISO 8601 ranges?

**Comment by braverock** [comment]
ISO 8601 doesn't specify any behavior ro a vector of ranges, so no such behavior has been implemented in xts. 

Have you considered using apply/lapply on your vector of time subsets and wrapping an rbind around that?  Should all be doable in one line of code, and I doubt is would be hard to understand later.

**Comment by joshuaulrich** [comment]
There is currently no way to pass in a vector of ranges.  Here's how I would approach it (off the top of my head):

```r
require(xts)
x <- xts(,.POSIXct(1:(86400*365), tz="UTC"))
want_subset <- c("T02:00:00/T02:14:59", "T04:15:00/T04:19:59")
system.time({
  i <- do.call(c, lapply(want_subset, function(i) x[i,which.i=TRUE]))
  y <- x[i,]
})
#    user  system elapsed 
#   5.380   1.016   6.396 
```

5-6s for 2 ranges of one year of one-second data on my laptop doesn't seem unreasonable.  If you provide a [reproducible example](http://stackoverflow.com/q/5963269/271616), including some sample data and your two work-around attempts, I can try to find a more efficient solution.

**Comment by michaelsbradleyjr** [comment]
@braverock that's essentially what I was doing (per my description of using `base::Map`), and found it too slow.

However, @joshuaulrich's showing `which.i` in action (I did not really appreciate that option previously) gave me some ideas on how to speed things up.

Thanks for your help. Feel free to close this issue.
