### ISSUE TITLE
to.monthly omits periods when some of the columns have NA values

### ISSUE THREAD

**Issue by debsush** [joshuaulrich/xts#145]
Hi,

I have an xts with first column containing daily price data from 2005 while the second column containing daily price data from 2008.  Using to.monthly delete all periods prior to 2008 since one of teh columns had Na values between 2005-2008.  Is there a way that I can get a monthly xts starting from 2005 onward or is it by design?

Regards,
SD

**Comment by joshuaulrich** [comment]
Please provide a reproducible example. It's hard to understand the issue based on only a description of the data and analysis. `to.period` is not designed to work on 2-column data. From `?to.monthly`:

> Convert an OHLC or univariate object to a specified periodicity lower than the given data object. For example, convert a daily series to a monthly series, or a monthly series to a yearly one, or a one minute series to an hourly series.

So the second column is being ignored.

```r
require(xts)
data(sample_matrix)
x <- to.monthly(sample_matrix[,1:2], name="foo")  # 2 columns
y <- to.monthly(sample_matrix[,1], name="foo")  # 1 column
identical(x,y)
# [1] TRUE
```

**Comment by DarrenCook** [comment]
You have NAs in the 2nd column, which causes those rows to be ignored. Run apply.monthly on just the column where you have full data, not on your whole object.  (I.e. that is the "univariate" that Joshua means).

**Comment by debsush** [comment]
Thank you Darren.
