### ISSUE TITLE
Unable to remove timestamp using to.period

### ISSUE THREAD

**Issue by debsush** [joshuaulrich/xts#149]
Hi,

I have an xts as attached
[test.txt](https://github.com/joshuaulrich/xts/files/366749/test.txt)
 
Now I am trying to transform this tick data into daily data.

If I use to.period, the aggregation is correct but the time stamp is not removed from the index 
DFDaily=to.period(DF,period="days",OHLC=TRUE,drop.time=TRUE)

DF.Open
DF.High
DF.Low
DF.Close
DF.Volume
2016-07-15 15:30:00
1172
1195
1058.3
1071
2706683

Please let me know what am I missing.  While I can use to.daily, the to.period allows me to use it conveniently within a function where I can pass the data and the period

Regards
SD

**Comment by joshuaulrich** [comment]
A text file is not an xts object. And your text file contains no date and/or time, so it's not possible for me to create an xts object from it.

And I've told you before, GitHub issues are not the place to ask questions about how to use the software.  Please respect that.
