### ISSUE TITLE
to.frequency is not working as expected

### ISSUE THREAD

**Issue by cloudcell** [joshuaulrich/xts#150]
1) This line https://github.com/joshuaulrich/xts/blob/master/R/toperiod.R#L264 sets the first value of bins to zero. This seems to be wrong for cases in which the first record has a value greater than the frequency set in the variable k. I.e. a valid 'endpoint' might be skipped incorrectly.

2) The first endpoint is being skipped
* get this [data](https://usercontent.irccloud-cdn.com/file/HFwmHOpH/GBPUSD.RData)
* use this code: `xts:::to.frequency(GBPUSD,by=GBPUSD$Volume,k=50)`
* screenshot of the analysis
![first_endpoint_skipped_](https://cloud.githubusercontent.com/assets/4019314/17767236/d41d8978-6537-11e6-9eda-81b18b6b46bb.png)

**Comment by cloudcell** [comment]
Fixed. See pull request #151.
Demonstration of the behavior after the fix:
![image](https://cloud.githubusercontent.com/assets/4019314/17788145/e5b76d22-6594-11e6-8a27-bddc5c34a855.png)

**Comment by joshuaulrich** [comment]
Here's a more minimal example that demonstrates the bug:

```r
require(xts)
data(sample_matrix)
x <- as.xts(sample_matrix)
x$Volume <- 1
xts:::to.frequency(x, x$Volume, 90)
#                Open     High      Low    Close Volume
# 2007-06-30 48.90488 50.33781 47.09144 47.76719     90
ep <- c(0L, 90L, 180L)
cnames <- c("Open", "High", "Low", "Close", "Volume")
.Call("toPeriod", x, ep, TRUE, 5L, FALSE, FALSE, cnames, PACKAGE="xts")
#                Open     High      Low    Close Volume
# 2007-04-01 50.03978 51.32342 48.23648 48.87032     90
# 2007-06-30 48.90488 50.33781 47.09144 47.76719     90
```

You can see that the `xts:::to.frequency` result is missing the first group.
