### ISSUE TITLE
Import zoo (or at least be explicit about the namespace)

### ISSUE THREAD

**Issue by christophsax** [joshuaulrich/xts#162]
Don't know if you have thought about it before, but this would make it much easier for other packages to use functionality from xts.

xts `Depends` on the zoo package, which makes it hard for other packages to import xts. If you try to import xts, and call, e.g., `as.xts.ts()`, through `xts::as.xts()`, this wouldn't work, because the zoo function `as.yearmon` cannot be found. Everything works if you depend on xts, of course.

The dygraph package by @jjallaire & co circumvent the problem by importing and re-exporting the functions from zoo, see [here](https://github.com/rstudio/dygraphs/blob/master/R/exports.R). 

This solves the problem for the moment, but it now makes it hard to import the dygraph package, and all packages that depend on it.

Because I want to write a package that is importable and depends on dygraph, I [hacked](https://github.com/christophsax/seasonalview/blob/master/R/importable-xts.R) some versions of the xts functions which are calling the zoo functions by its namespace. With this, the package is now importable.

But a much easier solution would be for the xts package to import zoo, rather than to depend on it. Or if you really want to depend on it, you could be specific about the namespace, i.e., calling `zoo::as.yearmon`, rather than `as.yearmon`.

On a fist glance, it seems to be only the `as.yearmon` and `as.yearqtr` functions causing the trouble, so changing them to `zoo::as.yearmon` wouldn't be much of a pain.

If you want, I can also contribute and change it in a pull request.

**Comment by joshuaulrich** [comment]
What version of xts are you using? [`yearmon` and `yearqtr` are already imported](https://github.com/joshuaulrich/xts/blob/master/NAMESPACE#L205-L206) in the development version.

**Comment by christophsax** [comment]
Wow, that's great! I was using the CRAN Version, 0.9.7. Any idea when this will be out? 
Thanks!
