### ISSUE TITLE
invalid ylim when plotting an xts object of 0s

### ISSUE THREAD

**Issue by rossb34** [joshuaulrich/xts#164]
Reproducible example
```r
plot(.xts(1:50, 1:50))
lines(.xts(rep(0,50), 1:50), on = NA)
```

We should check for this case and set the ylim to a reasonable value such as c(-1,1). We already do this in `plot.xts` so we should do it in `addSeries` as well.

**Comment by joshuaulrich** [comment]
Closing, since the referenced commit fixed this issue.
