### ISSUE TITLE
print.xts

### ISSUE THREAD

**Issue by ggrothendieck** [joshuaulrich/xts#167]
`print.xts` code includes this:

```
structure(structure(NULL, dim = dim(x)))
```

but NULL cannot have attributes.  See `?attr`

**Comment by joshuaulrich** [comment]
Thanks for the report.  Interesting that it doesn't throw an error.  Do you have a use case where this is an issue?

**Comment by ggrothendieck** [comment]
I don't have a specific instance where it caused a problem.  Just noticed it -- that's all.
