### ISSUE TITLE
toperiod.R: export(by.period, to.frequency) in NAMESPACE

### ISSUE THREAD

**Issue by silentbits** [joshuaulrich/xts#189]
https://github.com/joshuaulrich/xts/blob/master/R/toperiod.R#L207

https://github.com/joshuaulrich/xts/blob/master/R/toperiod.R#L221

why these functions are not exported in NAMESPACE?

**Comment by joshuaulrich** [comment]
Because I wrote them in a few minutes and they're not well tested.  We've used them for a few things, but I'm not comfortable making a commitment to maintain the API.  Also, please don't open an issue to ask a question.  Issues are for potential problems with the code, or to suggest a feature.

**Comment by silentbits** [comment]
> Also, please don't open an issue to ask a question. Issues are for potential problems with the code, or to suggest a feature.

I suggested in the topic to export them as a new a feature ("export(by.period, to.frequency) in NAMESPACE").

**Comment by joshuaulrich** [comment]
> I suggested in the topic to export them as a new feature ("export(by.period, to.frequency) in NAMESPACE").

Sorry, it wasn't clear to me you were suggesting exporting them as a feature.  Another reason they're not exported is because they're not documented.  So they need a solid specification, documentation, and tests before I would consider exporting them... and doing those things are not high on my priority list.

**Comment by joshuaulrich** [comment]
Another issue preventing these two functions from being exported: they both use functions from quantmod.  `by.period` has `on = Cl` by default, and `to.frequency` uses `has.Vo`, `has.Ad`, and `is.OHLC`.  This causes a circular dependency with quantmod.

**Comment by silentbits** [comment]
Josh...

`OHLC`, `has.Vo()`,  `has.Ad()`

https://github.com/joshuaulrich/xts/blob/master/NAMESPACE#L119
https://github.com/joshuaulrich/xts/blob/master/R/toperiod.R#L33

> This causes a circular dependency with quantmod.

https://github.com/joshuaulrich/xts/blob/master/R/OHLC.R#L22

**Comment by joshuaulrich** [comment]
Ah, good catch.  I didn't remember/realize copies of those functions were in xts.  Probably because I don't like the practice of duplicating code across packages.

**Comment by silentbits** [comment]
xts has very good support for OHLC, even without reference to quantmod:

https://github.com/joshuaulrich/xts/blob/master/src/toperiod.c

vs 10y old quantmod fortran code (to.period):

https://github.com/joshuaulrich/quantmod/tree/master/src
