### ISSUE TITLE
Very dense vertical grid ticks for long XTS objects

### ISSUE THREAD

**Issue by lompoc42** [joshuaulrich/xts#209]
I often work with long time-series data and before I updated to xts 0.10 I could run the following code without such densely packed vertical tick marks. They actually obscure much of the plot for me. Is this normal now? How do I get the vertical ticks to resemble what I used to see?

```r
idx = as.Date((Sys.Date()-10000):Sys.Date())
v1 = xts(rnorm(len(idx)), idx)
plot(v1)
```

**Comment by joshuaulrich** [comment]
Please don't file an issue to ask a question.  Use R-SIG-Finance or StackOverflow instead.

Use the `major.ticks` and `minor.ticks` to set tick intervals, as suggested in `?plot.xts`.

**Comment by lompoc42** [comment]
Apologies!
