### ISSUE TITLE
xout not working with na.locf

### ISSUE THREAD

**Issue by MortenGrum** [joshuaulrich/xts#215]
### Description

It seems xout is not working with na.locf()

### Expected behavior

That xout defines the timestamps of the output (as with na.approx() ) 

### Minimal, reproducible example

I have two xts time series data sets. One with my data and another with time stamps that I would like to use.

```r
xts_with_data <- as.xts(read.zoo(text='
2016-07-01 00:00:10,   1.0
2016-07-01 00:00:14,   2.0
2016-07-01 00:00:20,   3.0
2016-07-01 00:00:29,   4.0
2016-07-01 00:00:34,   5.0
2016-07-01 00:00:39,   6.0
', sep=',', index=1, tz='', format="%Y-%m-%d %H:%M:%S"))
names(xts_with_data) <- c('x')

xts_with_timestamps <- as.xts(read.zoo(text='
2016-07-01 00:00:15,   0.0
2016-07-01 00:00:20,   0.0
2016-07-01 00:00:30,   0.0
2016-07-01 00:00:35,   0.0
2016-07-01 00:00:38,   0.0
', sep=',', index=1, tz='', format="%Y-%m-%d %H:%M:%S"))

na.locf(xts_with_data, xout = index(xts_with_timestamps))
```
I would expect output like this
```r
                    [,1]
2016-07-01 00:00:15    2
2016-07-01 00:00:20    3
2016-07-01 00:00:30    4
2016-07-01 00:00:35    5
2016-07-01 00:00:38    5
```
but what I get is my original xts_with_data.
(it works as expected with na.approx() )

AkselA suggested (on stackoverflow) that ... "It seems like the source of your troubles is a missing feature in xts:::na.locf.xts. It might be worth letting Joshua (the developer) know, if he doesn't already." 

AkselA also pointed me to a couple of workaround:
```r
xts_all <- merge(xts_with_data, xts_with_timestamps)[,-2]
na.locf(xts_all)[index(xts_with_timestamps)]
# or
na.locf.default(xts_with_data, xout=index(xts_with_timestamps))
# or
na.locf(zoo(xts_with_data), xout=index(xts_with_timestamps))
```

(stackoverflow: https://stackoverflow.com/questions/47219803/last-observation-carried-forward-locf-on-xts-in-r-not-like-na-approx)

**Comment by joshuaulrich** [comment]
Thanks for the report!  I agree this is a bug.
