### ISSUE TITLE
plot.xts axis only shows two labels

### ISSUE THREAD

**Issue by eddelbuettel** [joshuaulrich/xts#246]
### Description

The x-axis annotation is somewhat overly sparse on irregular data

### Expected behavior

I would expect the usual four to five ticks to be shown

### Minimal, reproducible example

The image comes from running the example which requires the package. The same effect appears
just with the code not commented out here

```r
## library(RcppUTS)
## example(EMAnext)
##
## or directly:
suppressMessages(library(xts))
times <- ISOdatetime(2010, 1, 2, 8, 30, 0) + c(0, 1.0, 1.2, 2.3, 2.9, 5.0)
values <- seq(0, 10, by=2)
plot(xts(values, order.by=times), type="b",
         main="Series and last/next/linear EMAs")
#lines(xts(EMAlast(times,values, 1),  values, order.by=times),
#          type="b", col="lightblue")
#    lines(xts(EMAnext(times,values, 1),  values, order.by=times),
#          type="b", col="darkblue")
#   lines(xts(EMAlinear(times,values, 1),  values, order.by=times),
#          type="b", col="mediumblue")
    addLegend("topleft", legend.names=c("series", "EMAlast", "EMAnext", "EMAlinear"),
              lty=rep(1,4), lwd=rep(1,4),
              col=c("black", "lightblue", "darkblue", "mediumblue"))
```

will re-create the same plot shown on the [repository README.md](https://github.com/eddelbuettel/rcpputs) and here:

![image](https://user-images.githubusercontent.com/673121/41251925-2465b790-6d81-11e8-8af6-c3d104c2958f.png)

### Session Info

Current CRAN versions of everything.

**Comment by eddelbuettel** [comment]
BTW I tried to research this in old issue tickets and did not see it posted.  My bad if I missed one. 
 
/cc @rossb34

**Comment by joshuaulrich** [comment]
Thanks for the report. This has bothered me too, but never enough to take a look.  Seems like the solution could be as simple as setting `major.ticks = "auto"` and `grid.ticks.on = "auto"` as the `plot.xts()` defaults.  It works for your example.

**Comment by eddelbuettel** [comment]
That helps indeed.  The documentation on those options and these values is a bit ... sparse.

**Comment by rossb34** [comment]
I agree with @joshuaulrich that setting the default arguments to "auto" for the grid and axis ticks is a good solution. The default is "months" which is only reasonable for several months of data on a daily or lower frequency. 

`plot.xts` uses `xts:::axTicksByTime2` which is a port from what is used in `quantmod::chart_Series`, also mentioned in #74.

**Comment by rossb34** [comment]
@eddelbuettel thanks for the note on documentation. I'll add language to improve the documentation.

**Comment by eddelbuettel** [comment]
I am also looking at what `rtsplot::rtsplot()` does -- and it is pretty compelling.  Just extended some intra-daily data from one to several days and it put weekdays on the axis.

**Comment by eddelbuettel** [comment]
Casual usage of both over the last couple of days with generally irregular data has `rtsplot()` as a winner.

I am sure there are counter-examples. I have not yet hit any.  I'll follow up if I do.
