### ISSUE TITLE
Unit tests fail only on macOS

### ISSUE THREAD

**Issue by joshuaulrich** [joshuaulrich/xts#266]
The following tests fail on macOS:

```
test.matrix_reclass 
test.matrix_reclass_subset_as.xts_j1
test.matrix_reclass_subset_matrix_j1
test.matrix_reclass_subset_reclass_j1
test.tbs_1999_to_2008_by_year_Date
test.tbs_1999_to_2008_by_year_retclassDate
test.tbs_1999_to_200801_by_month
test.tbs_1999_to_200801_by_month_Date
test.tbs_1999_to_200801_by_month_POSIXct
test.tbs_199901_to_2008_by_month
test.tbs_199901_to_2008_by_month_Date
test.tbs_199901_to_2008_by_month_POSIXct
test.tbs_199901_to_200801_by_month
test.tbs_199901_to_200801_by_month_Date
test.tbs_199901_to_200801_by_month_POSIXct
test.timeSeries_reclass
test.timeSeries_reclass_subset_reclass_j1
```

The above tests fail for both xts 0.11-0 and 0.11-1, but only on macOS.  My guess is that the failures are related to the changes to `[.xts`, including possibly `binsearch()` and `window_idx()`.

I won't have access to a Mac for a few days, so I'd appreciate thoughts / suggestions for what may be causing the regressions in the unit tests.

I've attached the output from running `rhub::check_on_macos()` in [artifacts.r-hub.io.tar.gz](https://github.com/joshuaulrich/xts/files/2319108/artifacts.r-hub.io.tar.gz).

**Comment by brodieG** [comment]
Sorry, don't have a lot of time right now, but maybe this will help:

<img width="719" alt="image" src="https://user-images.githubusercontent.com/6105908/44599470-6ec9e380-a7a4-11e8-92d6-f4bf6abe10c1.png">

This is for this test:

```
  checkIdentical(sample.timeSeries,reclass(try.xts(sample.timeSeries)))
```

```
R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] chron_2.3-52        xts_0.11-0          timeSeries_3042.102
[4] timeDate_3043.102   zoo_1.8-3           RUnit_0.4.32       

loaded via a namespace (and not attached):
 [1] quadprog_1.5-5  lattice_0.20-35 crayon_1.3.4    digest_0.6.15  
 [5] withr_2.1.2     grid_3.5.1      quantmod_0.4-13 diffobj_0.1.11 
 [9] curl_3.2        tseries_0.10-45 TTR_0.23-3      devtools_1.13.5
[13] tools_3.5.1     compiler_3.5.1  memoise_1.1.0   fts_0.9.9.1    
```

**Comment by joshuaulrich** [comment]
Thanks @brodieG! I have a feeling using a `.setUp` function that includes `Sys.setenv(TZ = "UTC")` will quiet the errors.  I would still like to know when this regression occurred.  `git bisect` would probably be useful here, starting from the 0.10-2 tag.

**Comment by joshuaulrich** [comment]
Gabor patched `remotes` so r-hub is working again.  So I added the `.setUp` function that sets the timezone to "UTC", and now get failures on Windows (both 32- and 64-bit).  Wonderful.

```
FAILURE in test.convert_matrix_to_xts:
 Error in checkIdentical(sample.xts, as.xts(sample.matrix)) : FALSE 
 
FAILURE in test.convert_matrix_to_xts_i1:
 Error in checkIdentical(sample.xts[1, ], as.xts(sample.matrix)[1, ]) : FALSE 
 
FAILURE in test.convert_matrix_to_xts_i1j1:
 Error in checkIdentical(sample.xts[1, 1], as.xts(sample.matrix)[1, 1]) : FALSE 
 
FAILURE in test.convert_matrix_to_xts_j1:
 Error in checkIdentical(sample.xts[, 1], as.xts(sample.matrix)[, 1]) : FALSE 
```

**Comment by brodieG** [comment]
Whack-a-mole!  So OS-X is working though?  Let me know if you still want me to run bisect.

**Comment by joshuaulrich** [comment]
@brodieG yes, it would help, thanks!

I'm going to do the same on Windows.  It looks like some timezone change in the code is causing the results to differ across platforms.  I develop on Linux, which explains why things are working on that platform.

**Comment by joshuaulrich** [comment]
All tests pass (except 1, unrelated) on Windows and Linux when I remove all the `.setUp()` and `.tearDown()` functions from the test files, and put their relevant contents in the file outside any function. So it looks like I was doing something that caused RUnit to act weird.
