### ISSUE TITLE
plot.xts: how to set log scale?

### ISSUE THREAD

**Issue by TomDriftwood** [joshuaulrich/xts#283]
### Description

I want to plot a chart with a log scale for the y-axis, but neither ylog=TRUE or log="y" works in plot.xts. How can I do this? Thanks, Tom

**Comment by ethanbsmith** [comment]
same as #103

**Comment by joshuaulrich** [comment]
Thanks @ethanbsmith. I'm going to close this as a duplicate, so we can keep any conversation in the same place.
