### ISSUE TITLE
Change license to LGPL

### ISSUE THREAD

**Issue by chuckcoleman** [joshuaulrich/xts#308]
### Description

The GNU Public License makes code that calls xts public domain and subject to GPL.

### Expected behavior

Change to GNU Limited Public License.  Changes to xts will remain public domain while letting proprietary code link to it. This will encourage proprietary developers to contribute enhancements to xts.

### Minimal, reproducible example

N/A

### Session Info

N/A

**Comment by braverock** [comment]
I think you may misunderstand the LGPL.

The LGPL would allow proprietary software companies to use and ship xts as part of commercial software without paying the creators for it, and *without* giving their enhancements or extensions back to the community.

The GPL allows you to take the code *internally* and do whatever you want with it, but if you distribute it to third parties, the GPL requires you to also make your code available under the GPL.  I think the current license does exactly what it is designed to do, and encourages people to share their non-proprietary code with the community.

See for example GNU's discussion of the LGPL:

https://www.gnu.org/licenses/why-not-lgpl.en.html

**Comment by joshuaulrich** [comment]
Closing, since this isn't something I can resolve with a code change. Please feel free to continue the discussion though.
