### ISSUE TITLE
.rbind.xts created unnecessary env variable?

### ISSUE THREAD

**Issue by harvey131** [joshuaulrich/xts#313]
### .rbind.xts created unnecessary env variable?

I do not understand why .rbind.xts needs to create a new environment on  line 99 of bind.R

"env <- new.env()"

Is this a piece of legacy code that can be removed?

**Comment by joshuaulrich** [comment]
Hi Harvey, thanks for the report! Your question is correct. That line appears in the very first commit of `.rbind.xts()`, but `env` is never used.
