### ISSUE TITLE
period.apply will change the index from "Date" to "POSIXct" type in xts 0.12.0 

### ISSUE THREAD

**Issue by testagaintestagain** [joshuaulrich/xts#341]
### Description

I caught this issue after upgrading from xts 0.11.2 to 0.12.0,
The **period.apply** will change the index from "Date" to "POSIXct" type (along with a timezone inconsistency warning). This behavior will cause problems as commented in the reproducible example below.

As I checked, the changes were triggered by changes in  .xts (called in reclass, which is used in period.apply)

### Minimal, reproducible example

```r
x <- xts(1:10, Sys.Date()+1:10)
xW <- apply.weekly(x, sum)
cat(class(index(x)), class(index(xW)))

# newIndex <- seq(index(xW[1]), index(xW[10]), by = 1) --> this dominates how this would cause problem

```

### Session Info

```r
R version 3.5.3 (2019-03-11)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    
```

**Comment by joshuaulrich** [comment]
I believe this is a duplicate of #322.  Please use the latest GitHub version to confirm.

**Comment by testagaintestagain** [comment]
Thanks for the quick response. You are right.

**Comment by joshuaulrich** [comment]
Great, thanks! Also, you can expect a new xts release over the weekend. It needs to be on CRAN by 9/9.  Make sure you re-install then to get the latest production release.

**Comment by testagaintestagain** [comment]
Great! Looking forward to it. And thanks for your amazing work. I have been using xts and TTR for more than 10 years.
