### ISSUE TITLE
Deleting time from the index of an xts object

### ISSUE THREAD

**Issue by avrenli2** [joshuaulrich/xts#370]
### Description

When I run the following code, the index of the xts object includes both date and time of day.

### Expected behavior

I would like the index of the xts object to only include the date; and **not time of day**.

### Minimal, reproducible example

```r
library(quantmod)
xts() -> HISTORY
c("SBUX","TSLA","CAKE") -> STOCKS
for (SYMBOL in STOCKS) {
  getSymbols(SYMBOL , from="2017-1-1" , to="2022-1-1" , auto.assign=F) -> PRICE
  monthlyReturn(PRICE[,6])  ->  RETURNS
  cbind(HISTORY,RETURNS) -> HISTORY
}

STOCKS -> colnames(HISTORY)
head(HISTORY)
```

### Session Info

```r
[Insert your sessionInfo() output]
```

**Comment by joshuaulrich** [comment]
The index has a time because you create `HISTORY <- xts()` and the default index for xts objects has a time. Set `HISTORY <- NULL` instead.
