### ISSUE TITLE
Control number of ticks on y-axis

### ISSUE THREAD

**Issue by FredrikWartenberg** [joshuaulrich/xts#374]
Hi Joshua,
I have a branch on a local clone of xts with a minor improvement to plot.xts allowing to increase the number of ticks on the y-axis. If it is of general interest, I'd like to make it a pull request, but I have no rights to push my branch.
regards,
Fredrik

From ?plot.xts
yticks.density

Density of tickmarks on y axis. The density will be increased by the given factor (default = 1). The number of tickmarks is determined by means of the pretty function with n = 5 * yticks.desnity.

**Comment by joshuaulrich** [comment]
Thanks for your contribution!

You have a couple options:

1. Fork this repo to create a copy under your account. Then make your changes on a branch in that repo. You can submit a pull request once they're committed and pushed to your forked copy.
2. Use the command line: `git checkout {your-branch-name} && git format-patch master`. That will create patch files you can send me.

Let me know if you need help with either of those.

**Comment by joshuaulrich** [comment]
@FredrikWartenberg I don't see a patch in your comment. If you attached it to your email, GitHub probably stripped it because you replied to an issue comment. You can send it to my personal email: `maintainer("xts")`.

**Comment by FredrikWartenberg** [comment]
[0001-Add-yticks.density-as-argument-to-plot-allowing-to-c.patch.gz](https://github.com/joshuaulrich/xts/files/9731337/0001-Add-yticks.density-as-argument-to-plot-allowing-to-c.patch.gz)

Hope it works this way
