### ISSUE TITLE
Noisy message when loaded by quantmod

### ISSUE THREAD

**Issue by dmurdoch** [joshuaulrich/xts#393]
You are now printing a big ugly message in your .onAttach function about the conflict between stats::lag and dplyr::lag.  That's a real issue, and it's a problem if I was using dplyr, but I'm not, I just have it installed.  I'm not even attaching xts, I'm just importing quantmod, and quantmod attaches it.  Don't you think that's excessive?

**Comment by dmurdoch** [comment]
A suggestion:  if dplyr is not already attached, just set a hook to give the message out if it is attached, e.g.

    setHook(packageEvent("dplyr", "attach"), function(...) uglyMessage())

**Comment by joshuaulrich** [comment]
@dmurdoch I've implemented your suggestion and added it to the main branch. Please let me know if there's anything else we can do to make sure the warning is only shown at appropriate times.

Thanks again for the report and fix!
