### ISSUE TITLE
[DOCS] - Query for 'xts' NEWS information shows up to version 0.7-5

### ISSUE THREAD

**Issue by cgiachalis** [joshuaulrich/xts#416]
### Description

Running  `news(package = "xts")` will show the news information up to version 0.7-5.

This is because from the next version v0.8-0, the header version was changed from ***“Changes in version”***  to ***“Changed in version”***.  

From `?news()`  and for plain text *...Entries are grouped according to version, with version header “Changes in version” at the beginning of a line..*

In addition, since v0.8-0 the news files (plain text) is mixed with markdown heading levels.

Perhaps, the NEWS can be converted to NEWS.md for more flexibility; I can send a PR for review if you want this change.

Thanks

**Comment by joshuaulrich** [comment]
Thanks for the suggestion! I'd appreciate a PR with those changes.
