### ISSUE TITLE
[R-Forge #1603] Can't use na.locf() on character data

### ISSUE THREAD

**Issue by joshuaulrich** [joshuaulrich/xts#42]
Submitted by: Ken Williams (@kenahoo)
Assigned to: Nobody
[R-Forge link](http://r-forge.r-project.org/tracker/index.php?func=detail&aid=1603&group_id=118&atid=516)

na.locf() seems to fail on xts objects containing character data:

> s1 <- xts(c('OK', 'Fail', NA, 'Service'), Sys.Date()+1:4)
> na.locf(s1)
> Error in na.locf.xts(s1) : unsupported type
> 
> s1 <- xts(c(1,2,NA,4), Sys.Date()+1:4)
> na.locf(s1)
>            [,1]
> 2011-09-28    1
> 2011-09-29    2
> 2011-09-30    2
> 2011-10-01    4

I can use na.locf.default() as a workaround, I don't seem to lose any fidelity in the process:

> s1 <- xts(c('OK', 'Fail', NA, 'Service'), Sys.Date()+1:4)
> na.locf.default(s1)
>            [,1]  
> 2011-09-28 'OK'  
> 2011-09-29 'Fail'  
> 2011-09-30 'Fail'  
> 2011-10-01 'Service'

 -Ken

**Comment by SamoPP** [comment]
Also seems that na.omit fails on all character data:
> na.omit(xts(c("a", "b", "c", NA, "d"), as.Date(1:5)))
Error in na.omit.xts(xts(c("a", "b", "c", NA, "d"), as.Date(1:5))) : 
  unsupported type

**Comment by Masutani** [comment]
xout option for na.locf / na.locf.default cannot work for character data (xts/zoo).

**Comment by joshuaulrich** [comment]
@kenahoo, I hope "better late than never" applies in this case!

I didn't address the n-way merge issue on character xts because I have some significant changes to the merge C code that I would like to incorporate first.
