### ISSUE TITLE
`addEventLines()` for multiple panels

### ISSUE THREAD

**Issue by ethanbsmith** [joshuaulrich/xts#420]
### Description

`addEventLines()` current only draws on a single panel or adds a new panel. this is cumbersome when needing to add the same even to multiple panels. eg, see attached image

### Expected behavior

would be nice if the `on` parameter either supported a vector of panels, or maybe a special value (like NULL) which would draw the event across all panels

### Minimal, reproducible example

![image](https://github.com/joshuaulrich/xts/assets/24379655/1d5aa854-1e2f-4ed8-b1ea-fe95b76afeca)

**Comment by joshuaulrich** [comment]
Thanks for the report. Here's an example.

```r
library(xts)
data(sample_matrix)
x <- as.xts(sample_matrix)
plot(x, multi.panel = TRUE)
addEventLines(xts("a", index(x)[10]), pos = 4)
```

Setting `on` to a vector of panel numbers errors. This also fails for `addLegend()`.

```r
addEventLines(xts("a", index(x)[10]), pos = 4, on = 1:4)
addLegend(on = 1:4)
```

**Comment by joshuaulrich** [comment]
@ethanbsmith please see if that patch works for you.

**Comment by ethanbsmith** [comment]
for the record, this crash under 4.4.0 was a build issue on my machine. works fine
