### ISSUE TITLE
[R-Forge #1602] Can't merge multiple objects with character values

### ISSUE THREAD

**Issue by joshuaulrich** [joshuaulrich/xts#44]
Submitted by: Ken Williams (@kenahoo)
Assigned to: Nobody
[R-Forge link](http://r-forge.r-project.org/tracker/index.php?func=detail&aid=1602&group_id=118&atid=516)

It appears that the merge() function fails when fed more than 2 xts objects, and they contains character data:

``` r
> x <- xts(letters[1:5], Sys.Date() + cumsum(1:5)*60)
> merge(x)
           [,1]
2011-09-28 'a' 
2011-09-30 'b' 
2011-10-03 'c' 
2011-10-07 'd' 
2011-10-12 'e' 
> merge(x,x)
           x   x.1
2011-09-28 'a' 'a'
2011-09-30 'b' 'b'
2011-10-03 'c' 'c'
2011-10-07 'd' 'd'
2011-10-12 'e' 'e'
> merge(x, x, x)
Error in merge.xts(x, x, x) : unsupported data type
```

By contrast, it works fine when the data is numeric:

``` r
> merge(x)
           [,1]
2011-09-28    1
2011-09-30    2
2011-10-03    3
2011-10-07    4
2011-10-12    5
> merge(x,x)
           x x.1
2011-09-28 1   1
2011-09-30 2   2
2011-10-03 3   3
2011-10-07 4   4
2011-10-12 5   5
> merge(x,x,x)
           x x.1 x.2
2011-09-28 1   1   1
2011-09-30 2   2   2
2011-10-03 3   3   3
2011-10-07 4   4   4
2011-10-12 5   5   5
```

Perhaps something's being silently converted to a factor internally?

 -Ken

**Comment by joshuaulrich** [comment]
The n-way merge case currently only works for logical, integer, and numeric types. Character, complex, and any other type will fail.  It should be possible to add support for character and complex data.

**Comment by Stevo15025** [comment]
Wanted to note this also effects `lag.xts()`. A workaround for that function is to do an `lapply()` over your lags and then bind them all together with `cbind.zoo()`

```{r}
library(xts)
library(lubridate)
set.seed(1234)
dat = data.frame(test_arima = arima.sim(model = list(ar = c(.5,.2), ma = c(.4), order = c(2,0,1)), n = 200))
times = (as.POSIXlt("1992-01-14")) + lubridate::days(1:200)
dat = xts(dat,order.by = times)

dat$change = ifelse(diff(dat[,1]) > .5, "up","down")
dat = dat[complete.cases(dat),]  
xLagDiff = lapply(1:lag,function(i) lag.xts(dat,k = i))
xLagDiff2 = do.call(cbind.zoo,xLagDiff)
dim(xLagDiff2)
```

**Comment by joshuaulrich** [comment]
@Stevo15025, your example doesn't run. `lag` is only defined as a function, so your `lapply` call fails.  Could you please edit your example to be *minimal* (i.e. without requiring another package and running an ARIMA model) and *reproducible* (runs from a clean R session).

**Comment by Stevo15025** [comment]
@joshuaulrich apologies, amended the example

**Comment by joshuaulrich** [comment]
@Stevo15025 awesome, thanks!

Note that this only affects `lag` because `lag` calls `merge` when `length(k)` is > 2.  In fact, it works if `length(k)` <= 2. For example:

```r
R> lag(dat,2:3)
           char char.1
1992-01-01 NA   NA    
1992-01-02 NA   NA    
1992-01-03 "A"  NA    
1992-01-04 "B"  "A"   
1992-01-05 "A"  "B"   
1992-01-06 "B"  "A"   
1992-01-07 "A"  "B"   
1992-01-08 "B"  "A"   
1992-01-09 "A"  "B"   
1992-01-10 "B"  "A"   
```

**Comment by Stevo15025** [comment]
@joshuaulrich also, on a completely unrelated note, on a scale of `1:10` how difficult would it be to write an `xts.table` package that inherits from data.table instead of zoo? 

I feel like, ya know, it's [CURRENT YEAR] and it's nice to have factors / multiple data types, but I like how xts works with dates. I completely understand that data.frames are too slow, but data.table is fast and nice and good!
