### ISSUE TITLE
plot.xts - ylim arg is not acknowledged in addSeries

### ISSUE THREAD

**Issue by rossb34** [joshuaulrich/xts#76]
The ylim arg is not acknowledged in ```lines()``` and ```points()```.

The following code snippet produces the attached plot
```r
data(edhec, package="PerformanceAnalytics")
plot(edhec[,1], type="h")
lines(edhec[,1], type="h", ylim=c(0,0.02))
points(edhec[,1], ylim=c(0,0.02))
```
![rplot](https://cloud.githubusercontent.com/assets/5797430/7105441/76384eda-e0de-11e4-9fde-806a9a7f9250.png)

**Comment by rossb34** [comment]
I'm having problems with passing things through dots (```...```) in ```lines()``` and ```points()```. To try to understand what is going on, I added ```print(match.call(expand.dots=TRUE))``` to the beginning of ```lines()``` and ```addSeries()```.

Here is the output
```r
> data(edhec, package="PerformanceAnalytics")
> plot(edhec[,1], type="h")
> lines(edhec[,1], type="h", ylim=c(0,1))
lines.xts(x = edhec[, 1], ylim = c(0, 1), type = "h")
addSeries(x = x, main = main, on = on, type = type, col = col, 
    lty = lty, lwd = lwd, pch = pch, ylim = ..1)
```
It looks like ```ylim``` is correct in ```lines()```, but is somehow getting mangled when it is passed to ```addSeries()```.

**Comment by joshuaulrich** [comment]
There are several problems:
- `...` are not passed to `chart.lines`
- `...` are not passed to the `lines` calls inside `chart.lines`
- `addSeries` always overwrites `ylim`

I've pushed a patch to the issue_76 branch.

**Comment by joshuaulrich** [comment]
As @rossb34 [commented in the above commit](https://github.com/joshuaulrich/xts/commit/b0e5d7ae6be92a7df6c75022e018f877a11fc7ac#commitcomment-10695414):

> We still need `lenv$ylim <- ylim` for the case where we compute `ylim <- range(lenv$xdata[xsubset], na.rm=TRUE)`. The expressions for y-axis grid lines and labels need `lenv$ylim`.
