### ISSUE TITLE
plot.xts - pch not passed for points

### ISSUE THREAD

**Issue by timelyportfolio** [joshuaulrich/xts#80]
Getting caught up here, but it seems in  bc4dc5493adb1d247062572f13894d289b9c806b that we lost the ability to pass `pch` for points in `plot.xts`.  However, `pch` does still get passed with `points()`.  I am happy to submit a pull but wanted to make sure that I was not missing anything before working on it.  To test, I am just using the code from `?plot.xts` and modified the `points(...)` to subtract 1 so that it is easier to see.  I would expect all points to be triangles.

```r
library(xts)
data(sample_matrix)
sample.xts <- as.xts(sample_matrix)

# plot the Close
plot(sample.xts[,"Close"],type="p",pch=3)
points(sample.xts[endpoints(sample.xts[,"Close"], on = "months"), "Close"]-1, 
             col="red", pch=17, on=1)
```
![image](https://cloud.githubusercontent.com/assets/837910/7300814/2677a0a2-e9a4-11e4-940c-c4e4d095cb39.png)

**Comment by joshuaulrich** [comment]
Thanks for the report.  I don't think the commit you reference contains a change that caused this behavior.  Instead, it looks like any arguments that aren't in the formals of `chart.lines` or stored in the `replot_xts` environment will not be acknowledged.

**Comment by timelyportfolio** [comment]
The commit fixes it, but probably in the incorrect way.

**Comment by joshuaulrich** [comment]
@timelyportfolio I just pushed a potential, more general, fix.  I'd appreciate some testing on your end to see if everything still works.

**Comment by timelyportfolio** [comment]
@joshuaulrich thanks, your solution is better and fixes the main issue, but introduces a different one.  `points()` in the example above no longer change based on `pch`.

**Comment by joshuaulrich** [comment]
@timelyportfolio Thanks for the testing.  Your proposed fix looks correct and shouldn't break anything.  However, that doesn't mean my potential solution doesn't leave other things broken.
