### ISSUE TITLE
plot.xts - examples with custom panel

### ISSUE THREAD

**Issue by timelyportfolio** [joshuaulrich/xts#82]
Are there any examples of `plot.xts` with custom panels?  It appears in the comments that this is still experimental, but I'd like to try it nevertheless.  I'll play with a modified `chart.lines` to experiment.

**Comment by rossb34** [comment]
The panel functionality does work. I have a few examples of working with custom panels in the sandbox folder in xtsExtra, but I am currently working on more that will make there way to http://joshuaulrich.github.io/xts/ when complete

**Comment by timelyportfolio** [comment]
I knew I had seen some examples but could not remember where.  Thanks for pointing me there.  I had done a [horizon panel for `xtsExtra`](http://timelyportfolio.blogspot.com/2012/08/horizon-plots-with-plotxts.html) that I would love to port over.  I'll take a shot at it.  It seems easy enough.

**Comment by joshuaulrich** [comment]
Famous last words, "It seems easy enough." :)

It would be great to have a horizon panel.  Looking forward to the PR!

**Comment by rossb34** [comment]
Examples added to http://joshuaulrich.github.io/xts/plotting_panels.html. Please take a look and feel free to ask questions about the panel functionality or request examples

**Comment by joshuaulrich** [comment]
Closing this as completed (based on the previous comment)
