### ISSUE TITLE
Add lines/points to current panel instead of a new panel

### ISSUE THREAD

**Issue by joshuaulrich** [joshuaulrich/xts#84]
Calls to `lines.xts` and `points.xts` currently add a new panel.  In other plotting systems, `lines` and `points`, usually add to the current plot.

These two functions should add to the current panel by default, and add to a different panel if specified by the `on` argument.  `addSeries` should continue to add data to a new panel.

**Comment by rossb34** [comment]
For consistency we should also have `addEventLines` and `addLegend` add to the current panel by default.
