### ISSUE TITLE
Only 12 lines plotted if object has more than 12 columns

### ISSUE THREAD

**Issue by joshuaulrich** [joshuaulrich/xts#87]
```r
library(xts)
data(sample_matrix)
x <- as.xts(sample_matrix)
y <- merge(x,x+1,x+2,x+3)
plot(y)
```
![image](https://cloud.githubusercontent.com/assets/1023193/7479749/468fc016-f329-11e4-881d-4f8231378444.png)

Unless you manually specify `col`: `plot(y, col=1:ncol(y))`

![image](https://cloud.githubusercontent.com/assets/1023193/7479774/67da2b62-f329-11e4-8c74-e446fa29c1bf.png)

This also manifests if `multi.panel=TRUE`.

**Comment by rossb34** [comment]
The default for color is `col=1:12` so that is why only the first 12 are plotted. We should check to see if `NCOL(x) > col` and either recycle the `col` or append new colors to the end of `col`. I think it makes the most sense to recycle the vector. Something like this should work

```
if(NCOL(x) > col)
  col <- rep(col, length.out=NCOL(x))
```

**Comment by joshuaulrich** [comment]
This still manifests for `plot(y, multi.panel=TRUE)`.

Also, the default color palette only contains 8 values, so 9:12 are the same as 1:4.  So we should either change the default from `col = 1:12` to `col = 1:8` or use something more sophisticated (e.g. `rainbow`).
