### ISSUE TITLE
Ensure functions that used to depend on packages being attached still work

### ISSUE THREAD

**Issue by joshuaulrich** [joshuaulrich/xts#92]
CRAN now encourages (requires?) packages use `requireNamespace` instead of `require` in order to help keep the user's `search()` path clean.  That means we need to ensure that functions that used to depend on packages being on the search path will still work if the package is loaded but not attached.

This certainly affects the `index` function, but might also affect other functions.  `grep requireN.* xts/R/*` provides a starting point of places to check.

**Comment by shrektan** [comment]
+1. Currently, if my package use `xts` functions, I have to explicitly depends on `xts`. or, my package might not work...

**Comment by joshuaulrich** [comment]
Closing this as fixed, since I have re-instated many of the unit tests for the affected packages.  The `its` package was also archived, so that's one less dependency to break. ;)
